import * as diff from 'diff';
import { renderMarkdown, transformLinks } from './md-utils';
import { Component } from 'obsidian';

/**
 * Purpose: diff.createPatch() returns a string indicating "\ no newline at end of file" if we don't have this
 * @param content 
 * @returns 
 */
export function ensureNewline(content: string) {
    return content.endsWith('\n') ? content : content + '\n';
}

/**
 * DEPRECATED
 * @param text1 
 * @param text2 
 * @returns 
 */
export async function getDiff(text1: string, text2: string) {
    const diffResult = diff.createPatch('filename', text1, text2);
    return diffResult
}

/**
 * We iterate through the list of changes here and add classes to it depending on whether it is 
 * newly-added or deleted.
 * Process: html -> format classes -> remove noise characters. 
 * 
 * Note: We avoid sanitising as it would remove the links auto-generated by marked. E.g. app://..../image.png would be removed by sanitize
 * @param changes diff.Change array that contains all changes made. 
 * @returns Sanitised html
 */
export async function formatDiffContent(changes: diff.Change[], srcPath: string, component: Component) {

    const htmlChanges = [];
    const parser = new DOMParser()

    for (const change of changes) {
        if (!change.value.trim()) continue;
        const content = transformLinks(change.value);
        const md = await renderMarkdown(content, srcPath, component)
        const htmlDoc = parser.parseFromString(md, "text/html");

        // Add classes to child elements instead of the body
        htmlDoc.body.querySelectorAll('*').forEach(element => {
            if (change.added) {
                element.classList.add("diff-insert");
            } else if (change.removed) {
                element.classList.add("diff-delete");
            }
        });

        htmlChanges.push(htmlDoc.body.innerHTML);
    }

    let finalHtmlString = "";
    for (const htmlChange of htmlChanges) {
        if (!htmlChange) {
            finalHtmlString += "<br>"
        } else {
            finalHtmlString += htmlChange;
        }
    }
    return finalHtmlString
}